add exercises cards
TOP10-ms-students/finalJSProject-yourEnergy pull request #11
Opened 2024-02-20 21:31 UTC by whitcr

2024-02-20 21:55 UTC, MaximNoritsyn submitted a review, later dismissed

2024-02-20 22:39 UTC, Olena-Horobets requested changes
залишила коменти. Також питання до назви exercise-group. це скоріше muscle-card, яка увійде в список muscle-list (відповідно найперший тег можні одразу робити li. А другий компонент скоріше exercise-card, що увійде в список exersice-list (зверстано ок, наркань нема) і найперший тег теж можні одразу робити li

2024-02-20 22:39 UTC, Olena-Horobets commented on src/css/exercise-group.css
> +.card-text-subtitle {
add opacity 0.4

2024-02-20 22:39 UTC, Olena-Horobets commented on src/css/exercise-group.css
> +.card-item::after {
не зовсім зрозуміло навіщо додавати :after для затемнення, коли на сам елемент можна дати градієнт через backgroung-image

2024-02-20 22:55 UTC, whitcr commented
> залишила коменти. Також питання до назви exercise-group. це скоріше muscle-card, яка увійде в список muscle-list (відповідно найперший тег можні одразу робити li. А другий компонент скоріше exercise-card, що увійде в список exersice-list (зверстано ок, наркань нема) і найперший тег теж можні одразу робити li

з приводу назв не знаю, але це ж не тільки до muscle, але й до всіх трьойх фільтрів. теги li зробив

2024-02-21 01:29 UTC, Olena-Horobets approved these changes, later dismissed

2024-02-21 10:35 UTC, ICxodnik approved these changes

2024-02-21 10:35 UTC, merged