mobile markup and css
TOP10-ms-students/finalJSProject-yourEnergy pull request #18
Opened 2024-02-21 11:49 UTC by YagovkinDmytro

2024-02-21 12:33 UTC, ICxodnik requested changes

2024-02-21 12:33 UTC, ICxodnik commented on src/css/hero.css
> +h1,
всі css що вже є мають бутит видалені, тут даже багато стилів з reset.css. Інші css що загальні, та можути вплинутти на стилі інших, маютьт бутит в загальних файлай. Тут файл hero.css це повна мішанина.

2024-02-21 12:33 UTC, ICxodnik commented on src/css/hero.css
> +/* .hero-right-side {
всі коментарі мають бутти видалені

2024-02-21 13:15 UTC, YagovkinDmytro commented on src/css/hero.css
> +h1,
Уже навел порядок сейчас добавлю

2024-02-22 06:36 UTC, ICxodnik commented on src/css/hero.css
> +.container {
у нас есть общий класс контейнер, если ты хотел изменить все контейнеры то вынеси это в базовый клас, где прописаны остальные его стили. Если ты хотел изменить только свой контейнер, то переименуй его для более уникального имени.

2024-02-22 06:37 UTC, ICxodnik commented on src/css/hero.css
> +  .container {
этот стиль для контейнера уже прописан

2024-02-22 11:53 UTC, whitcr approved these changes

2024-02-22 11:56 UTC, whitcr commented on src/css/hero.css
> +    border: 1px solid #242424;
не певен чи обовязково, але краще юзати var з variables.css для кольорів

2024-02-22 11:58 UTC, ICxodnik approved these changes

2024-02-22 11:58 UTC, merged