Update icons
TOP10-ms-students/finalJSProject-yourEnergy pull request #23
Opened 2024-02-21 21:56 UTC by Olena-Horobets

- More icons added to the sprite
- Existing icons updated to sprite icons
- Socials list made a partial (header, footer)
- Footer styles updated

2024-02-21 22:03 UTC, dm-zhuk submitted a review, later dismissed

2024-02-21 22:04 UTC, whitcr commented
![photo_2024-02-21_23-03-46](https://github.com/TOP10-ms-students/finalJSProject-yourEnergy/assets/94221288/3c644937-dc81-4428-87ee-3b7d94a7a954)


arrow.svg потрібно тоді в exercise.html замінити на свг спрайт, якщо видалили файл

2024-02-22 02:54 UTC, Olena-Horobets commented
> ![photo_2024-02-21_23-03-46](https://private-user-images.githubusercontent.com/94221288/306788522-3c644937-dc81-4428-87ee-3b7d94a7a954.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NzA3MDYsIm5iZiI6MTcwODU3MDQwNiwicGF0aCI6Ii85NDIyMTI4OC8zMDY3ODg1MjItM2M2NDQ5MzctZGM4MS00NDI4LTg3ZWUtM2I3ZDk0YTdhOTU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAyNTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzOGYyYWNjODA1ZmVjN2ZkNTQyNjQ2MThkNTAzYTljNjNlYTZmMGExYWJlODMwMzliMzYwYTcxMWFjYTdhYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d4LYtQ-ODtSR_LxHHVchmoEUTAVTF6KqFkKag2CSV14)
> 
> arrow.svg потрібно тоді в exercise.html замінити на свг спрайт, якщо видалили файл

дякую, виправила

2024-02-22 06:09 UTC, ICxodnik requested changes
убрать из енения в формативании, оставить только изменения

2024-02-22 07:21 UTC, dm-zhuk approved these changes

2024-02-22 09:25 UTC, ICxodnik approved these changes

2024-02-22 10:00 UTC, Maksym-Zyza approved these changes

2024-02-22 20:38 UTC, ICxodnik submitted a review, later dismissed

2024-02-22 20:52 UTC, ICxodnik approved these changes

2024-02-22 20:53 UTC, merged